version: '2'
services:
 zookeeper-3:
  image: zookeeper
  container_name: zookeeper-3
  restart: always
  network_mode: "host"
  ports:
    - 2181:2181
    - 2888:2888
    - 3888:3888
  volumes:
    - "/data/zookeeper/data:/data"
    - "/data/zookeeper/datalog:/datalog"
    - "/data/zookeeper/log:/log"
  environment:
    ZOO_MY_ID: 3
    ZOO_SERVERS: server.3=0.0.0.0:2888:3888;2181 server.5=172.16.208.11:2888:3888;2181 server.6=172.16.208.12:2888:3888;2181

