version: '2'
services:
 kafka:
  image: wurstmeister/kafka
  container_name: kafka-2
  network_mode: "host"
  restart: on-failure
  ports:
    - "9092:9092"
  environment:
   KAFKA_BROKER_ID: 2 
   KAFKA_ADVERTISED_HOST_NAME: 172.16.208.12
   KAFKA_ZOOKEEPER_CONNECT: 172.16.208.10:2181,172.16.208.11:2181,172.16.208.12:2181 
